cross_target_platform:
  - linux-64        # [linux and x86_64]
  - linux-aarch64   # [linux and (x86_64 or aarch64)]
  - linux-ppc64le   # [linux and (x86_64 or ppc64le)]
  - win-64          # [win and x86_64]
