{% if cross_target_platform is undefined %}
{% set cross_target_platform = target_platform %}
{% endif %}

package:
  name: nvcc
  version: {{ cuda_compiler_version }}

build:
  number: 26
  skip: {{ not (compiler("cuda").startswith("nvcc") and cuda_compiler_version == "11.8") }}

outputs:
  - name: {{ cuda_compiler }}_{{ cross_target_platform }}
    {% set script = "linux/install_nvcc.sh" %}     # [linux]
    {% set script = "windows/install_nvcc.bat" %}  # [win]
    script: {{ script }}
    build:
      ignore_run_exports_from:
        - {{ c_compiler }}_{{ cross_target_platform }}
      run_exports:
        strong:
          - {{ pin_compatible("cudatoolkit") }}
          - {{ pin_compatible(c_stdlib ~ "_" ~ cross_target_platform) }}  # [linux]
    requirements:
      build:      # [win]
        - m2-sed  # [win]
      host:
        # Needed to symlink libcuda into sysroot libs.
        - {{ c_compiler }}_{{ cross_target_platform }} {{ c_compiler_version }}.*       # [linux]
        - {{ c_compiler }}_{{ cross_target_platform }}                                  # [win]
        - {{ c_stdlib }}_{{ cross_target_platform }} {{ c_stdlib_version }}             # [linux]
        - {{ c_stdlib }}_{{ cross_target_platform }}                                    # [win]
        - cudatoolkit {{ cuda_compiler_version }}
      run:
        - {{ pin_compatible("cudatoolkit") }}
        - sed                                                                           # [linux]
        - {{ pin_compatible(c_stdlib ~ "_" ~ cross_target_platform) }}                  # [linux]
    test:
      requires:
        - {{ c_compiler }}_{{ cross_target_platform }} {{ c_compiler_version }}.*       # [linux]
        - {{ c_compiler }}_{{ cross_target_platform }}                                  # [win]
        # Host code is forwarded to a C++ compiler
        - {{ cxx_compiler }}_{{ cross_target_platform }} {{ cxx_compiler_version }}.*   # [linux]
        - {{ cxx_compiler }}_{{ cross_target_platform }}                                # [win]
      files:
        - test.cu
        - linux/test_nvcc.sh     # [linux]
        - windows\test_nvcc.bat  # [win]
      commands:
        - bash linux/test_nvcc.sh  # [linux and target_platform == cross_target_platform]
        - windows\test_nvcc.bat    # [win and target_platform == cross_target_platform]
    about:
      home: https://github.com/conda-forge/nvcc-feedstock
      license: BSD-3-Clause
      license_file: LICENSE.txt
      summary: A meta-package to enable the right nvcc.

about:
  home: https://github.com/conda-forge/nvcc-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A meta-package to enable the right nvcc.

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - dillon-cullinan
    - isuruf
    - jakirkham
    - kkraus14
    - mike-wendt
    - raydouglass
    - jaimergp
    - leofang
