{% set name = "nvcc" %}
{% set number = 14 %}

{% if cuda_compiler_version in (None, "None", True, False) %}
{% set cuda_major = 0 %}
{% set cuda_minor = 0 %}
{% set cuda_major_minor = (0, 0) %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.2").split(".")[0]|int %}
{% set cuda_minor = environ.get("cuda_compiler_version", "11.2").split(".")[1]|int %}
{% set cuda_major_minor = (cuda_major, cuda_minor) %}
{% endif %}

package:
  name: "{{ name }}"

build:
  number: {{ number }}
{% if cuda_major == 0
    or (target_platform == "linux-ppc64le" and cuda_major_minor != (10, 2))
    or (target_platform == "linux-aarch64" and (cuda_major != 11 or arm_variant_type != "sbsa")) %}
  skip: true
{% endif %}

outputs:
  - name: "{{ name }}_{{ target_platform }}"
    version: "{{ cuda_compiler_version }}"
    number: {{ number }}
    script: install_nvcc.sh   # [linux]
    script: windows/install_nvcc.bat  # [win]
    build:
      ignore_run_exports:
        - libgcc-ng
      run_exports:
        strong:
          - cudatoolkit {{ cuda_compiler_version }}|{{ cuda_compiler_version }}.*
{% if cdt_name == "cos7" %}       # [linux]
          - __glibc >=2.17        # [linux]
{% endif %}                       # [linux]
    requirements:
      build:      # [win]
        - m2-sed  # [win]
      host:
        # Needed to symlink libcuda into sysroot libs.
        - {{ compiler("c") }}
{% if cdt_name == "cos7" %}                    # [linux]
        - sysroot_{{ target_platform }} 2.17   # [linux]
        - __glibc >=2.17                       # [linux]
{% endif %}                                    # [linux]
      run:
        - sed                                  # [linux]
{% if cdt_name == "cos7" %}                    # [linux]
        - sysroot_{{ target_platform }} 2.17   # [linux]
        - __glibc >=2.17                       # [linux]
{% endif %}                                    # [linux]
    test:
      requires:
        - {{ compiler("c") }}
        # Host code is forwarded to a C++ compiler
        - {{ compiler("cxx") }}
{% if cdt_name == "cos7" %}                    # [linux]
        - sysroot_{{ target_platform }} 2.17   # [linux]
{% endif %}                                    # [linux]
      files:
        - test.cu
        - test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
      commands:
        - bash test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
    about:
      home: https://github.com/conda-forge/nvcc-feedstock
      license: BSD-3-Clause
      license_file: LICENSE.txt
      summary: A meta-package to enable the right nvcc.

about:
  home: https://github.com/conda-forge/nvcc-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A meta-package to enable the right nvcc.

extra:
  recipe-maintainers:
    - dillon-cullinan
    - isuruf
    - jakirkham
    - kkraus14
    - mike-wendt
    - raydouglass
    - jaimergp
    - leofang
