{% set name = "nvcc" %}
{% set number = 11 %}

package:
  name: "{{ name }}"

build:
  number: {{ number }}
  skip: true  # [osx or cuda_compiler_version == "None"]

outputs:
  - name: "{{ name }}_{{ target_platform }}"
    version: "{{ cuda_compiler_version }}"
    number: {{ number }}
    script: install_nvcc.sh   # [linux]
    script: windows/install_nvcc.bat  # [win]
    build:
      ignore_run_exports:
        - libgcc-ng
      run_exports:
        strong:
          - cudatoolkit {{ cuda_compiler_version }}|{{ cuda_compiler_version }}.*
          - __glibc >=2.17  # [linux and cuda_compiler_version == "11.0"]
    requirements:
      build:      # [win]
        - m2-sed  # [win]
      host:
        # Needed to symlink libcuda into sysroot libs.
        - {{ compiler("c") }}
        - sysroot_linux-64 2.17  # [linux and cuda_compiler_version == "11.0"]
        - __glibc >=2.17         # [linux and cuda_compiler_version == "11.0"]
      run:
        - sed                    # [linux]
        - sysroot_linux-64 2.17  # [linux and cuda_compiler_version == "11.0"]
        - __glibc >=2.17         # [linux and cuda_compiler_version == "11.0"]
    test:
      requires:
        - {{ compiler("c") }}
        # Host code is forwarded to a C++ compiler
        - {{ compiler("cxx") }}
        - sysroot_linux-64 2.17  # [linux and cuda_compiler_version == "11.0"]
      files:
        - test.cu
        - test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
      commands:
        - bash test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
    about:
      home: https://github.com/conda-forge/nvcc-feedstock
      license: BSD-3-Clause
      license_file: LICENSE.txt
      summary: A meta-package to enable the right nvcc.

about:
  home: https://github.com/conda-forge/nvcc-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A meta-package to enable the right nvcc.

extra:
  recipe-maintainers:
    - dillon-cullinan
    - isuruf
    - jakirkham
    - kkraus14
    - mike-wendt
    - raydouglass
    - jaimergp
